### PR TITLE
Dark Mode & Light Mode Added

### PR DESCRIPTION
**Pull request by Surajit0573**
Title : Add a dark mode
Issue : #49
Changes : Added Dark mode and Light mode toggle button & fixed few small UI bugs.

image
image
image
image

### CODE REVIEW

**Comment by Surajit0573** [comment]
Hi @JiyaGupta-cs, Please Review this PR.

**Comment by JiyaGupta-cs** [comment]
image

image

@Surajit0573 It is changing the position of the right sidebar and make use of black colour and make it look attractive

**Comment by Surajit0573** [comment]
Hi @JiyaGupta-cs, I resolved the position issue and changed the theme to black and blue.

**Comment by Surajit0573** [comment]
@JiyaGupta-cs please review this PR

**Comment by varshith257** [comment]
Can you provide the screenshot of the updated?

**Comment by Surajit0573** [comment]
> Can you provide the screenshot of the updated?

image
image
image

**Comment by varshith257** [comment]
Why don't you make use of the same dark mode color for all components?

**Comment by Surajit0573** [comment]
> Why don't you make use of the same dark mode color for all components?

can you explain it, which components are you talking about ?!

**Comment by varshith257** [comment]
Feed Section, Job mela, etc...please use same dark mode color across all components

**Comment by JiyaGupta-cs** [comment]
@Surajit0573 Please make it look attractive. 
image
Take reference from this

**Pull request closed without merging**
